# Generated by Django 4.2.2 on 2023-07-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myusers', '0012_delete_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='myusers.my_user')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taker', to='myusers.my_user')),
            ],
        ),
    ]
