# Generated by Django 4.2.2 on 2023-06-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0004_my_user_delete_book_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
