# Generated by Django 4.2.2 on 2023-06-29 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0010_my_user_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_chats', to='myusers.my_user')),
                ('taker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_chats', to='myusers.my_user')),
            ],
        ),
    ]
