# Generated by Django 4.2.2 on 2023-06-29 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myusers', '0011_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
